# Default values for elasticsearch-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: upmcenterprises/elasticsearch-operator
  tag: master
  pullPolicy: Always
#  pullSecret:
resources:
  limits:
    cpu: 150m
    memory: 160Mi
  requests:
    cpu: 100m
    memory: 128Mi
rbac:
  enabled: true
